[[main]]
identifier = "home"
name = "Home"
url = "/"

[[main]]
identifier = "streaming"
name = "Streaming Tips"
url = "streaming"

[[main]]
identifier = "holidays"
name = "Holidays"
url = "holidays

[[main]]
identifier = "bot"
name = "Twitch Bot"
url = "https://bot.alazymeme.com"