enableSharingButtons = true

[footer]
trademark = true
copyright = true
author = true

[logo]
logoText = "ALazyMeme"
logoHomeLink = "/"

[portrait]
path = "/img/avatar.png"
alt = "Avatar"

[[social]]
name = "github"
url = "https://github.com/ALazyMeme"

[[social]]
name = "reddit"
url = "https://www.reddit.com/user/alazymeme"

[[social]]
name = "steam"
url = "https://steamcommunity.com/id/alazymeme"

[[social]]
name = "twitch"
url = "https://twitch.tv/alazymeme"

[[social]]
name = "twitter"
url = "https://twitter.com/alazymeme"

[[social]]
name = "youtube"
url = "https://www.youtube.com/c/alazymeme"