baseURL = "https://alazymeme.com/"
title = "ALazyMeme"
languageCode = "en-au"
theme = "hello-friend-ng"
enableRobotsTXT = true
buildDrafts = true

[author]
  name = "ALazyMeme"

[params]
  enableSharingButtons = true

  [params.footer]
    trademark = true
    copyright = true
    author = true

  [params.logo]
    logoText = "ALazyMeme"
    logoHomeLink = "/"
  
  [params.portrait]
    path = "/img/avatar.png"
    alt = "Avatar"

  [[params.social]]
    name = "github"
    url = "https://github.com/ALazyMeme"

  [[params.social]]
    name = "reddit"
    url = "https://www.reddit.com/user/alazymeme"

  [[params.social]]
    name = "steam"
    url = "https://steamcommunity.com/id/alazymeme"

  [[params.social]]
    name = "twitch"
    url = "https://twitch.tv/alazymeme"

  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/alazymeme"

  [[params.social]]
    name = "youtube"
    url = "https://www.youtube.com/c/alazymeme"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "streaming"
    name = "Streaming Tips"
    weight = 2
    url = "/streaming/"

  [[menu.main]]
    identifier = "holidays"
    name = "Holidays"
    weight = 3
    url = "#"

  [[menu.main]]
    identifier = "bot"
    name = "Twitch Bot"
    url = "https://bot.alazymeme.com"
    weight = 4
