baseURL = "/"
title = "ALazyMeme"
languageCode = "en-us"
theme = "hello-friend-ng"
paginate = 10
enableEmoji = true
enableRobotsTXT = true

[blackfriday]
  hrefTargetBlank = true

[author]
  name = "ALazyMeme"

[params]
  disableReadOtherPosts = false
  enableSharingButtons = false
  enableGlobalLanguageMenu = true


  [params.logo]
    logoText = "ALazyMeme"
    logoHomeLink = "/"

  [params.portrait]
    path = "/img/avatar.png"
    alt = "Avatar"

  [[params.social]]
    name = "github"
    url = "https://github.com/ALazyMeme"

  [[params.social]]
    name = "reddit"
    url = "https://www.reddit.com/user/alazymeme"

  [[params.social]]
    name = "steam"
    url = "https://steamcommunity.com/id/alazymeme"

  [[params.social]]
    name = "twitch"
    url = "https://twitch.tv/alazymeme"

  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/alazymeme"

  [[params.social]]
    name = "youtube"
    url = "https://www.youtube.com/c/alazymeme"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"

  [[menu.main]]
    identifier = "bot"
    name = "Twitch Bot"
    url = "https://bot.alazymeme.com"