baseURL = "/"
title = "ALazyMeme"
languageCode = "en-us"
theme = "hello-friend-ng"
paginate = 10
copyright = "&copy; ALazyMeme. All rights reserved."
enableEmoji = true
enableGitInfo = true

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"
  disableReadOtherPosts = false
  enableSharingButtons = false

  [[params.social]]
    name = "github"
    url = "https://github.com/ALazyMeme"

  [[params.social]]
    name = "reddit"
    url = "https://www.reddit.com/user/alazymeme"

  [[params.social]]
    name = "steam"
    url = "https://steamcommunity.com/id/alazymeme"

  [[params.social]]
    name = "twitch"
    url = "https://twitch.tv/alazymeme"

  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/alazymeme"

  [[params.social]]
    name = "youtube"
    url = "https://www.youtube.com/c/alazymeme"

[languages]
  [languages.en]
    title = "ALazyMeme"

    [languages.en.params.logo]
      logoText = "ALazyMeme"
      logoHomeLink = "/"

[menu]
  [[menu.main]]
    identifier = "home"
    name       = "Home"
    url        = "/"

  [[menu.main]]
    identifier = "streaming"
    name       = "Streaming Tips"
    url        = "/streaming"

  [[menu.main]]
    identifier = "bot"
    name       = "Twitch Bot"
    url        = "https://bot.alazymeme.com"